services:
    server:
        image: 'nginx:stable-alpine'
        ports:
            - '8000:80'
        volumes:
            - ./src:/var/www/html
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - php
    php:
        build:
            context: ./src
            dockerfile: php.dockerfile
        volumes:
            - ./src:/var/www/html:delegated
        depends_on:
            - mysql
    mysql:
        image: mysql
        env_file:
            - ./env/mysql.env
    composer:
        build:
            context: ./dockerfiles
            dockerfile: composer.dockerfile
        volumes:
            - ./src:/var/www/html
